SELECT DEPTNO,decode(deptno,10,'ACCOUNTING',20,'RESEARCH',30,'SALES')AS DNAME,
SUM(SAL) AS SAL
FROM SCOTT.EMP
WHERE SAL > 2000
GROUP BY DEPTNO 
ORDER BY 1;

SELECT DEPTNO,GREATEST(SUM(SAL),5000)AS SAL
FROM SCOTT.EMP
WHERE SAL>2000
GROUP BY DEPTNO 
ORDER BY 1;

SELECT CASE WHEN DEPTNO IN (10,20) THEN 1020 ELSE 3040  END AS DEPTNO
,SUM(SAL) AS SAL
FROM SCOTT.EMP
GROUP BY CASE WHEN DEPTNO IN (10,20) THEN 1020 ELSE 3040 END
ORDER BY 1;

SELECT * FROM SCOTT.EMP;


SELECT TO_CHAR(HIREDATE ,'YYYY-MM-DD') AS hiredate,sum(sal) AS sal
FROM scott.emp
GROUP BY to_char(hiredate,'YYYY-MM-DD')
ORDER BY 1;


SELECT DEPTNO,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL>2000
GROUP BY ROLLUP(DEPTNO)
ORDER BY 1
;


SELECT DEPTNO,JOB,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL > 2000
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY 1,2;


SELECT DEPTNO,JOB,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL>2000
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY 1,2;

SELECT DEPTNO,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL>2000
GROUP BY CUBE(DEPTNO)
ORDER BY 1;

SELECT DEPTNO,JOB,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL >2000
GROUP BY CUBE(DEPTNO,JOB)
ORDER  BY 1,2;

SELECT DEPTNO,JOB,COUNT(*) AS C1
FROM SCOTT.EMP
WHERE SAL >2000
GROUP BY CUBE(DEPTNO,JOB)
ORDER BY 1,2;

SELECT DEPTNO,JOB,COUNT(*) 
FROM SCOTT.EMP
