--조인
SELECT A.DEPTNO,A.DNAME,B.ENAME
FROM SCOTT.DEPT A,SCOTT.EMP B
WHERE B.DEPTNO = A.DEPTNO;

--인라인 뷰
SELECT A.C1 AS A,B.C1 AS B,C.C1 AS C,D.C1 AS D
FROM (T1 A LEFT OUTER JOIN T2 B ON B.C1 = A.C1)
LEFT OUTER JOIN (T3 C LEFT OUTER JOIN T4 D ON C.C1 =D.C1)
ON D.C1 = A.C1;

SELECT * FROM SCOTT.EMP;

SELECT DEPTNO,
	   MIN(SAL +NVL(COMM,0)) AS SAL_MIN,
	   MAX(SAL +NVL(COMM,0)) AS SAL_MAX
FROM SCOTT.EMP e
GROUP BY DEPTNO;

DEPTNO,SAL_MIN,SAL_MAAX
30		950		 2850
20		800	     3000
10		1300	 5000
;

