WITH w1 AS (select 'ABC' AS C1 FROM DUAL UNION ALL
			SELECT 'A%C' AS C1 FROM DUAL )
SELECT C1 FROM W1 WHERE C1 LIKE '_\%_' ESCAPE '\';	--	A%C

SELECT * FROM SCOTT.EMP;
SELECT ENAME FROM SCOTT.EMP WHERE 'AGENT SMITH' LIKE '%'||ENAME||'%'; --SMITH

SELECT ENAME FROM SCOTT.EMP WHERE INSTR('AGENT SMITH',ENAME)>0; --SMITH

SELECT ENAME,HIREDATE FROM SCOTT.EMP WHERE HIREDATE LIKE '1980%';

-- INTERNAL_FUNCTION >> HIREDATE가 문자값으로 변경된다.
SELECT ENAME,HIREADTE FROM SCOTT.EMP WHERE INTERNAL_FUNCTION (HIREDATE) LIKE '1980%';

