--NVL
SELECT NVL(1,2) AS C1,NVL(NULL,2) AS C2 FROM DUAL;

SELECT ENAME,SAL,COMM,SAL + COMM AS C1, 
	   SAL + NVL(COMM,0) AS C2
FROM SCOTT.EMP;


SELECT COLESCE(1,2,3) AS C1,
	   COLESCE(NULL,2,3) AS C2,
	   COLESCE(NULL,NULL,3) AS C3
FROM DUAL;	   