--SUBQUERY FACTORING

WITH W1 AS (SELECT DEPTNO,SUM(SAL) AS SAL FROM SCOTT.EMP GROUP BY DEPTNO)
SELECT A.DEPTNO,B.DNAME,A.SAL
FROM W1 A,SCOTT.DEPT B
WHERE B.DEPTNO = A.DEPTNO;


WITH W1 AS (SELECT DEPTNO,SUM(SAL) AS SAL FROM SCOTT.EMP GROUP BY DEPTNO)
	,W2 AS (SELECT SUM(SAL) AS SAL FROM W1)
SELECT A.DEPTNO,A.DNAME,B.SAL,(B.SAL/C.SAL) * 100 AS RT
FROM SCOTT.DEPT A,W1 B,W2 C
WHERE B.DEPTNO = A.DEPTNO;


--PL/SQL 선언 -->실행이 안됨.
WITH 
	FUNCTION f1 (i_val in VARCHAR2) RETURN NUMBER IS
		l_val NUMBER;
	BEGIN
		EXECUTE IMMEDIATE 'SELECT' || i_val ||'FROM DUAL' INTO l_val;
		RETURN l_val;
END;

