CREATE TABLE t1(c1 NUMBER NOT NULL,c2 NUMBER NOT null);
CREATE TABLE t2 (c1 NUMBER NOT NULL, c2 NUMBER);

INSERT INTO T1 VALUES(1,2);
INSERT INTO T1 VALUES(2,1);
INSERT INTO T1 VALUES(2,3);
INSERT INTO T1 VALUES(3,4);
INSERT INTO T2 VALUES(1,2);
INSERT INTO T2 VALUES(2,3);
INSERT INTO T2 VALUES(2,NULL);

COMMIT;

SELECT * FROM T1 
WHERE c1 = (SELECT max(c1) FROM t2)
AND c2 =(SELECT max(c2) FROM t2);

SELECT * FROM T1 WHERE (C1,C2) =(SELECT MAX(c1),MAX(C2) FROM T2);

SELECT a.* FROM t1 a WHERE a.c2 = (SELECT max(x.c2) FROM t2 x WHERE x.c1 = a.c1);

SELECT a.* FROM t1 a WHERE exists(SELECT 1 FROM t2 x WHERE x.c1 = a.c1);

--슈도코드
FOR a IN (SELECT * FROM t1) LOOP
	FOR b IN (SELECT * FROM T2 b WHERE b.c1 = a.c1) LOOP
		EXIT;
	end LOOP;
END LOOP;
-- >> 실행이 안된다..

SELECT a.*
FROM t1 a
WHERE exists(SELECT 1 FROM dual WHERE a.c1 = 2 UNION ALL
			 SELECT 1 FROM t2 x WHERE x.c2 =a.c2);
			
			
SELECT a.* FROM t1 a WHERE exists(SELECT 1 FROM t2 x WHERE x.c1 = c1);

SELECT a.* FROM t1 a WHERE NOT exists(SELECT 1 FROM t2 x WHERE a.c1 <>2 AND x.c2 = a.c2);

SELECT * FROM SCOTT.EMP;

SELECT MIN(HIREDATE) KEEP(DENSE_RANK FIRST ORDER BY SAL) AS C1 -- 정렬된 행 그룹에서 최저 순위 행을 지정
	  ,MAX(HIREDATE) KEEP(DENSE_RANK FIRST ORDER BY SAL) AS C2 -- 정렬된 행 그룹에서 최고 순위 행을 지정
	  ,MIN(HIREDATE) KEEP(DENSE_RANK LAST ORDER BY SAL) AS C3
	  ,MAX(HIREDATE) KEEP(DENSE_RANK LAST ORDER BY SAL) AS C4
FROM SCOTT.EMP
WHERE DEPTNO = 20;



SELECT A.* 
FROM T1 A
WHERE (SELECT MAX(X.C2) FROM T2 X WHERE X.C1 =A.C1) >=3;

SELECT *
 FROM T1 A
 WHERE exists(SELECT 1 FROM t2 x WHERE x.c1 = a.c1);
 
SELECT * FROM t1 WHERE c1 in(SELECT c1 FROM t2 GROUP BY c1 HAVING max(c2)>=3);


--스칼라 서브 쿼리
SELECT a.c1,(SELECT max(x.c2) FROM t2 x WHERE x.c1 = a.c1) AS c2 FROM t1 a;

SELECT A.DEPTNO,A.DNAME
	,(SELECT MIN(X.SAL) FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO) AS SAL_MIN
	,(SELECT MAX(X.SAL) FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO) AS SAL_MAX
FROM SCOTT.DEPT A;


SELECT A.DEPTNO,A.DNAME
	,NVL((SELECT SUM(X.SAL) FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO),0) AS SAL
	,CASE 
		WHEN (SELECT SUM(X.SAL) FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO) >= 10000
		THEN 1
		ELSE 2
	END AS GRADE
FROM SCOTT.DEPT A;

--인라인 뷰
SELECT A.DNAME,B.ENAME
FROM (SELECT * FROM SCOTT.DEPT WHERE LOC='DALLAS') A
     ,(SELECT * FROM SCOTT.EMP WHERE JOB='CLERK') B
WHERE B.DEPTNO =A.DEPTNO;

SELECT A.DNAME,B.SAL
FROM SCOTT.DEPT A
	,(SELECT DEPTNO,SUM(SAL) AS SAL FROM SCOTT.EMP GROUP BY DEPTNO) B
WHERE B.DEPTNO = A.DEPTNO;

--중첩 서브쿼리
SELECT A.DEPTNO,A.DNAME
FROM SCOTT.DEPT A
WHERE EXISTS(SELECT 1 FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO);

SELECT A.DEPTNO,A.DNAME
FROM SCOTT.DEPT A
WHERE EXISTS(SELECT 1 FROM SCOTT.EMP X WHERE X.DEPTNO =A.DEPTNO);

SELECT A.DEPTNO,A.DNAME
FROM SCOTT.DEPT A
	,(SELECT DISTINCT DEPTNO FROM SCOTT.EMP) B
WHERE B.DEPTNO = A.DEPTNO;

--스칼라 서브쿼리
SELECT A.DEPTNO,
	   A.DNAME,
	  (SELECT MIN(SAL) FROM SCOTT.EMP X WHERE X.DEPTNO =A.DEPTNO) AS SAL_MIN,
	  (SELECT MAX(SAL) FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO) AS SAL_MAX
FROM SCOTT.DEPT A;


SELECT A.DEPTNO,A.DNAME,B.SAL_MIN,B.SAL_MAX
FROM SCOTT.DEPT A
	,(SELECT DEPTNO, MIN(SAL) AS SAL_MIN, MAX(SAL) AS SAL_MAX
	  FROM SCOTT.EMP 
	  GROUP BY DEPTNO) B
WHERE B.DEPTNO(+) = A.DEPTNO;

SELECT * FROM SCOTT.EMP; --SAL

SELECT A.DEPTNO,A.DNAME,MIN(SAL) AS SAL_MIN,MAX(SAL) AS SAL_MAX
FROM  SCOTT.DEPT A, SCOTT.EMP B
WHERE B.DEPTNO (+) = A.DEPTNO
GROUP BY A.DEPTNO,A.DNAME;


SELECT A.EMPNO,B.ENAME
	  ,(SELECT X.DNAME FROM SCOTT.EMP X WHERE X.DEPTNO = A.DEPTNO) AS DNAME
FROM SCOTT.EMP A;

SELECT A.EMPNO,A.ENAME,B.DNAME
FROM SCOTT.EMP A,SCOTT.DEPT B
WHERE B.DEPTNO(+) = A.DEPTNO
AND B.LOC(+) = 'DALLAS';

SELECT A.EMPNO,A.ENAME,B.DNAME
FROM SCOTT.EMP A
WH





